# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "SCANPY_HASHSOLO"
description: Probabilistic demultiplexing of cell hashing data
keywords:
  - anndata
  - single-cell
  - hashing
  - demultiplexing
  - scanpy
tools:
  - "scanpy":
      description: "Single-cell analysis in Python. Scales to >100M cells."
      homepage: "https://github.com/scverse/scanpy"
      documentation: "https://scanpy.readthedocs.io/en/stable/generated/scanpy.external.pp.hashsolo.html"
      tool_dev_url: "https://github.com/scverse/scanpy"
      doi: "10.1186/s13059-017-1382-0"
      licence: ["BSD-3"]
      identifier: biotools:scanpy

input:
  - use_10x:
      type: boolean
      description: |
        Whether to read hashing input in 10x mtx format (`true`) or H5AD (`false`).
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - hto_data_10x:
        type: directory
        description: |
          Input directory containing hashing count matrix in 10x mtx format (matrix.mtx, features.tsv, barcodes.tsv).
          Can be `[]` if `use_10x` is `false`.
        ontologies:
          - edam: "http://edamontology.org/data_3917" # count matrix
    - hto_data_h5ad:
        type: file
        description: |
          AnnData object containing hashing counts in `.obs`.
          Can be `[]` if `use_10x` is `true`, as the data is retrieved from the 10x input.
        pattern: "*.{h5ad}"
        ontologies:
          - edam: "http://edamontology.org/format_3590" # HDF5 format
    - cell_hashing_columns:
        type: list
        description: |
          Groovy list (`['hash_1', 'hash_2']`) of `.obs` columns that contain cell hashing.
          Can be `[]` if `use_10x` is `true` because column are inferred from 10x input.

output:
  assignment:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*_hashsolo.csv":
          type: file
          description: |
            CSV file containing hashsolo assignment results
          pattern: "*_hashsolo.csv"
          ontologies:
            - edam: http://edamontology.org/format_3752 # CSV
  h5ad:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*_hashsolo.h5ad":
          type: file
          description: |
            Processed AnnData object containing hashsolo results
          pattern: "*_hashsolo.h5ad"
          ontologies:
            - edam: "http://edamontology.org/format_3590" # HDF5 format
  params:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
          pattern: "*_params_hashsolo.csv"
      - "*_params_hashsolo.csv":
          type: file
          description: |
            CSV file containing parameters used in hashsolo analysis
          pattern: "*_params_hashsolo.csv"
          ontologies:
            - edam: http://edamontology.org/format_3752 # CSV
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@seohyonkim"
  - "@LuisHeinzlmeier"
maintainers:
  - "@seohyonkim"
  - "@LuisHeinzlmeier"
