# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "SCANPY_HASHSOLO"
description: Probabilistic demultiplexing of cell hashing data
keywords:
  - anndata
  - single-cell
  - hashing
  - demultiplexing
  - scanpy
tools:
  - "scanpy":
      description: "Single-cell analysis in Python. Scales to >100M cells."
      homepage: "https://github.com/scverse/scanpy"
      documentation: "https://scanpy.readthedocs.io/en/stable/generated/scanpy.external.pp.hashsolo.html"
      tool_dev_url: "https://github.com/scverse/scanpy"
      doi: "10.1186/s13059-017-1382-0"
      licence: ["BSD-3"]
      identifier: biotools:scanpy

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - hto_data:
        type: file
        description: |
          Input directory containing hashing count matrix in 10x mtx format.
        pattern: "*"
        ontologies: []

output:
  assignment:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
          pattern: "*_hashsolo.csv"
      - "*_hashsolo.csv":
          type: file
          description: |
            CSV file containing hashsolo assignment results
          pattern: "*_hashsolo.csv"
          ontologies:
            - edam: http://edamontology.org/format_3752 # CSV
  plot:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
          pattern: "*_hashsolo.jpg"
      - "*_hashsolo.jpg":
          type: file
          description: |
            QC plot images from hashsolo analysis
          pattern: "*_hashsolo.jpg"
          ontologies:
            - edam: http://edamontology.org/format_3579 # JPEG
  h5ad:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
          pattern: "*_hashsolo.h5ad"
      - "*_hashsolo.h5ad":
          type: file
          description: |
            Processed AnnData object containing hashsolo results
          pattern: "*_hashsolo.h5ad"
          ontologies:
            - edam: http://edamontology.org/format_3591 # H5AD
  params:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test' ]
          pattern: "*_params_hashsolo.csv"
      - "*_params_hashsolo.csv":
          type: file
          description: |
            CSV file containing parameters used in hashsolo analysis
          pattern: "*_params_hashsolo.csv"
          ontologies:
            - edam: http://edamontology.org/format_3752 # CSV
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
authors:
  - "@seohyonkim"
maintainers:
  - "@seohyonkim"
