---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
- bioconda::dropletutils-scripts=0.0.5
- bioconda::r-seurat=3.0.2
