---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
<<<<<<< HEAD
- bioconda::bioconductor-dropletutils=1.26.0
- conda-forge::r-seurat=5.3.0
=======
- bioconda::dropletutils-scripts=0.0.5
- bioconda::r-seurat=3.0.2
>>>>>>> 11d1bc9b0 (save changes)
