---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
<<<<<<< HEAD
<<<<<<< HEAD
  - "conda-forge::r-seurat=5.3.0"
  - "conda-forge::r-seuratobject=5.1.0"
=======
  # TODO nf-core: List required Conda package(s).
  #               Software MUST be pinned to channel (i.e. "bioconda"), version (i.e. "1.10").
  #               For Conda, the build (i.e. "h9402c20_2") must be EXCLUDED to support installation on different operating systems.
  - "bioconda::r-seurat=3.0.2"
>>>>>>> 83d76b1b1 (push test)
=======
  - "conda-forge::r-seurat=5.3.0"
  - "conda-forge::r-seuratobject=5.1.0"
>>>>>>> 9f906916c (remove last TODO)
