---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "htodemux"
description: Demultiplex samples based on data from cell hashing.
keywords:
  - demultiplexing
  - hashing-based deconvoltion
  - single-cell
tools:
  - "htodemux":
      description: "HTODemux is the demultiplexing module of Seurat, which demultiplex samples based on data from cell hashing."
      homepage: "https://satijalab.org/seurat/articles/hashing_vignette"
      documentation: "https://satijalab.org/seurat/reference/htodemux"
      tool_dev_url: "https://github.com/satijalab/seurat"
      doi: "10.1186/s13059-018-1603-1"
      licence: ["GPL v3"] #?????
      identifier: "" #?????

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - seurat_object:
        type: file
        description: |
          A `.rds` file containing the seurat object. Assumes that the hash tag oligo (HTO) data has been added and normalized.

output:
  - csv:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.csv":
          type: file
          description: CSV's for the classification, assignment and parameters.
          pattern: "*.csv"
  - rds:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.rds":
          type: file
          description: SeuratObject saves as RDS.
          pattern: "*.rds"

  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@LuisHeinzlmeier"
maintainers:
  - "@LuisHeinzlmeier"
