---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "htodemux"
<<<<<<< HEAD
<<<<<<< HEAD
description: Demultiplex samples based on data from cell hashing.
keywords:
  - demultiplexing
  - hashing-based deconvolution
  - single-cell
tools:
  - "htodemux":
      description: "HTODemux is the demultiplexing module of Seurat, which demultiplex samples based on data from cell hashing."
      homepage: "https://satijalab.org/seurat/articles/hashing_vignette"
      documentation: "https://satijalab.org/seurat/reference/htodemux"
      tool_dev_url: "https://github.com/satijalab/seurat"
      doi: "10.1186/s13059-018-1603-1"
      licence: ["MIT"]
      identifier: ""

input:
=======
## TODO nf-core: Add a description of the module and list keywords
description: write your description here
=======
description: Demultiplex samples based on data from cell hashing.
>>>>>>> b885950c9 (address None issue)
keywords:
  - demultiplexing
  - hashing-based deconvoltion
  - single-cell
tools:
  - "htodemux":
      ## TODO nf-core: Add a description and other details for the software below
      description: "A toolkit for quality control, analysis, and exploration of single cell RNA sequencing data. 'Seurat' aims to enable users to identify and interpret sources of heterogeneity from single cell transcriptomic measurements, and to integrate diverse types of single cell data. See Satija R, Farrell J, Gennert D, et al (2015) <doi:10.1038/nbt.3192>, Macosko E, Basu A, Satija R, et al (2015) <doi:10.1016/j.cell.2015.05.002>, and Butler A and Satija R (2017) <doi:10.1101/164889> for more details." #?????
      homepage: "https://satijalab.org/seurat/articles/hashing_vignette"
      documentation: "https://satijalab.org/seurat/reference/htodemux"
      tool_dev_url: "https://github.com/satijalab/seurat"
      doi: "10.1186/s13059-018-1603-1"
      licence: ["GPL v3"] #?????
      identifier: "" #?????

## TODO nf-core: Add a description of all of the variables used as input
input:
  # Only when we have meta
>>>>>>> 83d76b1b1 (push test)
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - seurat_object:
        type: file
        description: |
          A `.rds` file containing the seurat object. Assumes that the hash tag oligo (HTO) data has been added and normalized.
<<<<<<< HEAD
    - assay:
        type: string
        description: |
          Name of the Hashtag assay, usually called "HTO" by default. Use the custom name if the assay has been named differently.
output:
  - params:
=======

## TODO nf-core: Add a description of all of the variables used as output
output:
  - bam:
      #Only when we have meta
>>>>>>> 83d76b1b1 (push test)
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
<<<<<<< HEAD
      - "*_params_htodemux.csv":
          type: file
          description: The used parameters to call HTODemux in the R-Script.
          pattern: "params_htodemux.csv"

  - assignment:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*_assignment_htodemux.csv":
          type: file
          description: Assignment results.
          pattern: "assignment_htodemux.csv"

  - classification:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*_classification_htodemux.csv":
          type: file
          description: Classification results.
          pattern: "classification_htodemux.csv"

  - rds:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*_htodemux.rds":
          type: file
          description: SeuratObject saved as RDS.
          pattern: "htodemux.rds"
=======
      ## TODO nf-core: Delete / customise this example output
      - "*.bam":
          type: file
          description: Sorted BAM/CRAM/SAM file
          pattern: "*.{bam,cram,sam}"
          ontologies:
            - edam: "http://edamontology.org/format_2572" # BAM
            - edam: "http://edamontology.org/format_2573" # CRAM
            - edam: "http://edamontology.org/format_3462" # SAM
>>>>>>> 83d76b1b1 (push test)

  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@LuisHeinzlmeier"
maintainers:
  - "@LuisHeinzlmeier"
